name: 'Commit Message Clarity Rating'
description: 'Use Llama.cpp to rate the clarity of a commit message.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token for authentication'
    required: true
  LLAMA_URL:
    description: 'Llama.cpp API URL'
    required: true
  OWNER:
    description: 'Repository owner'
    required: false
    default: ${{ github.repository_owner }}
  REPO:
    description: 'Repository name'
    required: false
    default: ${{ github.repository }}
  PR_NUMBER:
    description: 'Pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      if: github.repository != 'rate-my-pr/clarity'
      with:
        repository: rate-my-pr/clarity
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-action-${{ hashFiles('main.py') }}
        restore-keys: |
          ${{ runner.os }}-action-
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - run: python main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LLAMA_URL: ${{ inputs.LLAMA_URL }}
        OWNER: ${{ inputs.OWNER }}
        REPO: ${{ inputs.REPO }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
